### ISSUE TITLE
Operation speed problem

### ISSUE THREAD

**Issue by yuxitong** [udacity/CarND-Advanced-Lane-Lines#19]
I don't know why. When I ran this project, I found it was very slow.

The video will take 24 minutes and 34 seconds. I don't know how fast you are.

**Comment by mvirgo** [comment]
Hi there!

That is a fairly slow runtime, although typically this particular algorithm is not normally real-time either  - I usually see around 4-5 fps to generate the video. I'd consider checking whether you have any unnecessary steps or loops (like re-calibrating each time, or similar).

Otherwise, please note that you should look for project help on Knowledge or Student Hub, as Issues here should be related to broken things or inconsistencies within the starter code.

**Comment by JimKimHome** [comment]
you don't have to do cv2.calibrateCamera()  method in every frame,you just have to do it once, after that , FPS can reach 4
